apiVersion: v1
kind: Secret
metadata:
  name: thumbworx-db-secret
type: Opaque
stringData:
  DB_DATABASE: project_starter
  DB_USERNAME: starter_user
  DB_PASSWORD: starter_password
  DB_ROOT_PASSWORD: root_password
