name: Thumbworx CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Backend
        working-directory: backend
        run: composer install --no-interaction --prefer-dist

      - name: Build Frontend Docker
        run: docker build -t thumbworx-frontend ./frontend

      - name: Build Backend Docker
        run: docker build -t thumbworx-backend ./backend

      - name: Build AI Docker
        run: docker build -t thumbworx-ai-service ./ai-service